name: Cross-Platform Game Testing

on:
  push:

jobs:
    test:
      name: Test for ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
  
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            override: true
          
        - name: Run Tests
          uses: actions-rs/cargo@v1
          with:
            command: test
            args: --release